### ISSUE TITLE
Multiplayer Issues

### ISSUE THREAD

**Issue by dbennett3321** [Mako88/dxx-tracker#38]
I am not able to get a two pc's on different networks to join into a game together unless I use Hamachi. Both PC's can host and be seen on the tracker but cant see each other or other games on the in game list. LAN also works well. Just TCP connection without the aid of Hamachi is the issue.

**Comment by vLKp** [comment]
This project is only the source for the tracker service that the game clients notify in order to coordinate the existence of games.  Connectivity problems between the games would be a client issue, and better tracked in https://github.com/dxx-rebirth/dxx-rebirth/ .

As an aside, the games use UDP, not TCP, for game-to-game communication.  The default game data port is 42424, but this can be changed by the individual systems.

**Comment by Mako88** [comment]
I've just completely rebuilt the tracker from the ground up. If you're still experiencing issues with the new tracker, feel free to re-open this ticket!
